# fly.toml app configuration file generated for tumbaspedia-dev on 2023-05-08T06:38:34+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tumbaspedia-dev"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true

[[services]]
  [services.concurrency]
    type = "requests"
    hard_limit = 1000
    soft_limit = 1000

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/api"
    protocol = "http"
